### ISSUE TITLE
Add More Detailed OS Version For Windows

### ISSUE THREAD

**Issue by Jack-Works** [libcala/whoami#19]
In PowerShell it's

> \[Environment\]::OSVersion.ToString()

Microsoft Windows NT 10.0.18363.0

**Comment by AldaronLau** [comment]
`distro()` gets the most detailed version name currently supported.  I'm imagining there's a way to do it with the WinAPI, so I'll look into adding this eventually, unless you or someone else wants to take it up first.

**Comment by AldaronLau** [comment]
WhoAmI 1.0.2 now returns a more detailed OS version, so closing.
