### ISSUE TITLE
Bug during compilation

### ISSUE THREAD

**Issue by ylann10** [libcala/whoami#22]
Hi,

I get a compile time error while using the "username" function. I can't find a way to solve this problem, do you have any idea?

Thanking you

**Return from rustc:**

_error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
  |
  = note: "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "-nostartfiles" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\self-contained\\crt2.o" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-L" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\self-contained" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.109c28khmx95elvc.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.1223k2d4v02qj3ms.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.17yqc9mqzjrsf9oq.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.1bayprrlqypl9j4g.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.1ihzmeil77tmmheb.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.1j7pcsv9ba1ytggy.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.2222yq4vudnwfpaj.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.24r2k4wruxgdydrv.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.27ib1kwb6p7uut02.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.28nldai6tecqsv1d.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.2935chmc4l8qtm2h.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.2a5qdfrtq65iwlwp.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.2gh22ofplwye86pt.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.2k78uxgyypon0jb3.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.2mkua32ge31crvil.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.2ocl1ietcwdam1r8.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.2v5i5y9zjvywd8vg.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.2wrlojn0fbodm7v5.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.2wsj3ffg9y4v82lt.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.2ykxa8jp4x2sm6gi.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.32dco5oaguw2wl4m.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.33gmezpffj91sj9f.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.33tckxcg5mkvs3du.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.3a95b73ytfglm501.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.3e1j851t8u6lqf0y.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.3j10ohoj1kla7pxz.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.3k4lf65i6x0p0mvs.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.3pp4dnxmsfgkfqt0.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.3qpnutkseyzpz2u9.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.3swarsyehecwmzd8.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.3v4pedk5zr3575co.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.3v4rwo7ad1sg5kw1.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.48ohn8ysmbi9u4dn.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.49j9n3c63lqznw1o.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.49naylhxr6gqll22.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.4dyg2acl8kmzb9xz.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.4fm5rtps0kgoubj1.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.4fzcreygkyx1t6q1.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.4h66vdrgtqsnllj0.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.4ijwvuqdllv5pk55.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.4xrxjqpv6uxayr0p.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.555wf0858r8ebps0.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.a3xiakg01qyquvc.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.cqshyrlzawft44k.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.kxhju3a67d69xmt.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.ncnppctqanudlkr.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.neu9m21ekb8q0wt.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.r4gi9xwfrt9jjqq.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.s2pncqniqzcfogb.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.tlujmru701k9g7g.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.u90zuka6a8e0agx.rcgu.o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.yujrwp2tqt44dhu.rcgu.o" "-o" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.exe" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\client-a1919aa5cdcab024.1oigcjupep789ln3.rcgu.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps" "-L" "C:\\Users\\%USERNAME%\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\winapi-x86_64-pc-windows-gnu-0.4.0\\lib" "-L" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,-Bstatic" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\libjson-a26e1aa48bcfbdec.rlib" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\libdirs-d5eed462948b9cb3.rlib" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\libdirs_sys-3497b7a942ce20bf.rlib" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\libwinapi-bab88ce11a64d9b5.rlib" "D:\\Users\\%USERNAME%\\Desktop\\Toto\\Rust\\Program\\Client\\target\\debug\\deps\\libwhoami-cf504303bec067aa.rlib" "-Wl,--start-group" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-c1f4a34954f44b86.rlib" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-63d918f6a4328727.rlib" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libobject-df02665a14c23c3f.rlib" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libaddr2line-8a2ca8def5625c96.rlib" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgimli-f8602c621ed79cb5.rlib" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-8124381f500c8a69.rlib" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-2260daa86b23c242.rlib" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-5b3ec382765aebe0.rlib" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-58f1a51695d3489d.rlib" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-46b81e008718457e.rlib" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-f4a48eaff8400529.rlib" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-7094347f61afa1d3.rlib" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-be0238fd280e8b76.rlib" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-bb3b979426878ebc.rlib" "-Wl,--end-group" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-021a8bc03364b43c.rlib" "-Wl,-Bdynamic" "-lwinapi_advapi32" "-lwinapi_cfgmgr32" "-lwinapi_gdi32" "-lwinapi_kernel32" "-lwinapi_msimg32" "-lwinapi_ole32" "-lwinapi_opengl32" "-lwinapi_shell32" "-lwinapi_user32" "-lwinapi_winspool" "-lsecur32" "-lntdll" "-lkernel32" "-ladvapi32" "-lws2_32" "-luserenv" "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\Users\\%USERNAME%\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: ld: cannot find -lntdll_

**Comment by AldaronLau** [comment]
@ylann10 Interesting, I think it might have to do with using the mingw toolchain, which I should add to the GitHub actions, so it doesn't break again.  Could you try the msvc toolchain and see if that works?  I'll look into solutions for this.

**Comment by AldaronLau** [comment]
@ylann10 This is now fixed in version 1.1.1, so closing.
