### ISSUE TITLE
can't build on windows 7

### ISSUE THREAD

**Issue by rfyiamcool** [libcala/whoami#26]
please see snapshop. `whoami` don't support windows 7 ? 😁

![](https://z3.ax1x.com/2021/07/30/WOT49x.png)

**Comment by AldaronLau** [comment]
@rfyiamcool It looks like the patch I made for https://github.com/libcala/whoami/issues/22 to support linking under MINGW is causing your issue.  I'm not sure why it's giving you `error 5` (permission denied)?  The build.rs basically just checks `C:\windows\system32` as a rust-link-search path.

Can you try cloning the repository and commenting out the `println!()` in the Cargo.toml and see if that fixes it?

**Comment by rfyiamcool** [comment]
😅 😅 😅

I didn't do anything. I just rebooted，now it's ok.  

thank you @AldaronLau
