### ISSUE TITLE
Android wapm crash at missing /etc/os-release

### ISSUE THREAD

**Issue by truboxl** [libcala/whoami#28]
**Describe the bug**
Tried building Android version wapm which uses whoami, getting crashes when running wapm on Android
Not sure how to try experiment patching as I am unfamiliar how cargo works
Deps and all are picked up by cargo automatically

**To Reproduce**
Unlikely to suggest a very fast way to set up as I am using a complex environment
But it will be a good try to see what happens when /etc/os-release does not exist which is true for Android

**Expected behavior**
Should not crash

**Screenshots**
![Screenshot_20210923-152546_Termux](https://user-images.githubusercontent.com/12658589/134470051-cc341b60-4274-46c3-93aa-fe9dddc8a211.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy A30s
 - OS: Android
 - Browser Chrome? Not relevant
 - Version 11

**Additional context**
Tried upgrading from whoami 0.5.3 to whoami 1.1.3 in wapm still stuck here

**Comment by AldaronLau** [comment]
@truboxl Thanks, for opening the issue!  I'll look into fixing it.

**Comment by AldaronLau** [comment]
@truboxl Do you want to test #29?  It should fix the issue.

**Comment by truboxl** [comment]
Wow that works! wapm no longer crashes 🤣 
Took me quite some time to really understand how to patch using cargo and manifest file
https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#working-with-an-unpublished-minor-version
https://github.com/rust-lang/cargo/issues/8690

Screenshot:
![Screenshot_20210926-122520_Termux](https://user-images.githubusercontent.com/12658589/134793811-61080d17-b06e-4c0c-9fa9-9b94a5a69822.jpg)

I think you can close this once landed
I think I will submit PR at wasmer side to use the latest whoami

**Comment by AldaronLau** [comment]
@truboxl Just released version 1.1.4 released with the patch.
