### ISSUE TITLE
Potential segfault / memory safety issue in getpwuid

### ISSUE THREAD

**Issue by sphw** [libcala/whoami#32]
I discovered this bug while running `sqlx` in a minimal docker image that did not contain a `passwd` file. When a record is not found for a user, `whoami` segfaults. 

This is due to `whoami` incorrectly handling this case. According to the [man page for `getpwuid_r`](https://linux.die.net/man/3/getpwuid_r) when no entry is found in the passwd file, the status will still equal 0. Crucially, `result` will be set to `NULL`, and no write will occur into `pwd`. That leaves `passwd` uninitialized and makes `assume_init` an unsafe call that can trigger undefined behavior. 

I believe I have fixed this problem in https://github.com/libcala/whoami/pull/33

**Reproduction steps**
1. Enter an environment without a `passwd file
2. Run some code that relies on `getpwuid`
3. Observe segfault

**Comment by AldaronLau** [comment]
@sphw whoami 1.1.5 just released with your fix

**Comment by sphw** [comment]
@AldaronLau Thank you for the quick approval, and even faster release!
